USE ResearchLabManager;

-- GRANT Table
CREATE TABLE `GRANT` (
	GID INT PRIMARY KEY,
	P_DURATION INT,
	AGENCY VARCHAR(150),
	BUDGET DECIMAL(15,2),
	START_DATE DATE,
	PID INT,

	FOREIGN KEY (PID) REFERENCES PROJECT(PID)
		ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- EQUIPMENT Table
CREATE TABLE EQUIPMENT (
	EID INT PRIMARY KEY,
	E_TYPE VARCHAR(100),
	E_NAME VARCHAR(150),
	MANUAL TEXT
);

-- DEVICE Table
CREATE TABLE DEVICE (
	DID INT,
	EID INT,
	STATUS VARCHAR(30),
	P_DATE DATE,

	PRIMARY KEY (DID, EID),
    
    FOREIGN KEY (EID) REFERENCES EQUIPMENT(EID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- USES Relationship
CREATE TABLE USES (
	MID INT,
	DID INT,
	EID INT,
	S_DATE DATE,
	E_DATE DATE,
	PURPOSE VARCHAR(255),

	PRIMARY KEY (MID, DID, EID, S_DATE),
    
	FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (DID, EID) REFERENCES DEVICE(DID, EID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- PUBLICATION Table
CREATE TABLE PUBLICATION (
	PUBID INT PRIMARY KEY,
	TITLE VARCHAR(255),
	VENUE VARCHAR(200),
	DATE DATE,
	DOI VARCHAR(100)
);

-- PUBLISHES Relationship
CREATE TABLE PUBLISHES (
	MID INT,
	PUBID INT,

	PRIMARY KEY (MID, PUBID),
    
	FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY (PUBID) REFERENCES PUBLICATION(PUBID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
    
);

DELIMITER //

-- Prevent more than 3 members using a device at the same time (INSERT)
CREATE TRIGGER trg_uses_max_three_before_insert
BEFORE INSERT ON USES
FOR EACH ROW
BEGIN
	DECLARE active_count INT;
	SELECT COUNT(*) INTO active_count
	FROM USES
	WHERE DID = NEW.DID AND EID = NEW.EID
		AND (E_DATE IS NULL OR E_DATE >= NEW.S_DATE)
		AND (NEW.E_DATE IS NULL OR NEW.S_DATE <= IFNULL(E_DATE, '9999-12-31'));
	IF active_count >= 3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'A device cannot be used by more than 3 lab members simultaneously';
	END IF;
END //

-- Prevent more than 3 members using a device at the same time (UPDATE)
CREATE TRIGGER trg_uses_max_three_before_update
BEFORE UPDATE ON USES
FOR EACH ROW
BEGIN
	DECLARE active_count INT;
	SELECT COUNT(*) INTO active_count
	FROM USES
	WHERE DID = NEW.DID AND EID = NEW.EID AND MID != NEW.MID
		AND (E_DATE IS NULL OR E_DATE >= NEW.S_DATE)
		AND (NEW.E_DATE IS NULL OR NEW.S_DATE <= IFNULL(E_DATE, '9999-12-31'));
	IF active_count >= 3 THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'A device cannot be used by more than 3 lab members simultaneously';
	END IF;
END //

-- Auto update DEVICE STATUS to 'In Use' when a usage is inserted
CREATE TRIGGER trg_device_status_on_uses_insert
AFTER INSERT ON USES
FOR EACH ROW
BEGIN
	IF NEW.E_DATE IS NULL THEN
		UPDATE DEVICE SET STATUS = 'In Use'
		WHERE DID = NEW.DID AND EID = NEW.EID;
	END IF;
END //

-- Auto update DEVICE STATUS to 'Available' when usage ends
CREATE TRIGGER trg_device_status_on_uses_update
AFTER UPDATE ON USES
FOR EACH ROW
BEGIN
	DECLARE still_in_use INT;
	IF NEW.E_DATE IS NOT NULL AND OLD.E_DATE IS NULL THEN
		SELECT COUNT(*) INTO still_in_use
		FROM USES
		WHERE DID = NEW.DID AND EID = NEW.EID
			AND E_DATE IS NULL AND MID != NEW.MID;
		IF still_in_use = 0 THEN
			UPDATE DEVICE SET STATUS = 'Available'
			WHERE DID = NEW.DID AND EID = NEW.EID;
		END IF;
	END IF;
END //

DELIMITER ;
