-- CREATE DATABASE
CREATE DATABASE ResearchLabManager;
USE ResearchLabManager;

-- CREATE TABLES
-- Lab Member Class and Subclasses
CREATE TABLE LAB_MEMBER (
	MID INT PRIMARY KEY,
	NAME VARCHAR(100),
    JOIN_DATE DATE,
    TYPE VARCHAR(20) NOT NULL CHECK (TYPE IN ('Student', 'Faculty', 'Collaborator')),
    MENTOR INT,
    M_SDATE DATE,
    M_EDATE DATE,

    FOREIGN KEY (MENTOR) REFERENCES LAB_MEMBER(MID)
		ON DELETE SET NULL
        ON UPDATE CASCADE
);
CREATE TABLE STUDENT (
    MID INT PRIMARY KEY,
    SID INT,
    LEVEL VARCHAR(20),
    MAJOR VARCHAR(100),

    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE FACULTY (
    MID INT PRIMARY KEY,
    DEPARTMENT VARCHAR(100),

    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);
CREATE TABLE COLLABORATOR (
    MID INT PRIMARY KEY,
    AFFILIATION VARCHAR(150),
    CV TEXT,

    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Project Class
CREATE TABLE PROJECT (
    PID INT PRIMARY KEY,
    TITLE VARCHAR(150),
    S_DATE DATE,
    E_DATE DATE,
    E_DURATION INT CHECK (E_DURATION >= 0), # Number of Days
    STATUS VARCHAR(20) CHECK (STATUS IN ('Active', 'Completed', 'Paused')),
    LEADER INT NOT NULL,
    
    FOREIGN KEY (LEADER) REFERENCES FACULTY(MID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- Works Class
CREATE TABLE WORKS (
    PID INT,
    MID INT,
    ROLE VARCHAR(50),
    HOURS INT,

    PRIMARY KEY (PID, MID),
    FOREIGN KEY (PID) REFERENCES PROJECT(PID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);

DELIMITER //
CREATE TRIGGER insert_no_student_mentor_faculty
BEFORE INSERT ON LAB_MEMBER
FOR EACH ROW
BEGIN
    IF 
		NEW.TYPE = 'Faculty' 
          AND NEW.MENTOR IS NOT NULL 
          AND EXISTS( 
			SELECT	*
			FROM	LAB_MEMBER
			WHERE	MID = NEW.MENTOR 
				AND TYPE = 'Student'
		  )
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Students cannot mentor faculty members';
	END IF;
END //

CREATE TRIGGER update_no_student_mentor_faculty
BEFORE UPDATE ON LAB_MEMBER
FOR EACH ROW
BEGIN
    IF 
		(NEW.TYPE = 'Faculty' 
          AND NEW.MENTOR IS NOT NULL 
          AND EXISTS( 
			SELECT	*
			FROM	LAB_MEMBER
			WHERE	MID = NEW.MENTOR 
				AND TYPE = 'Student'
		  ))
          OR
          (NEW.TYPE = 'Student' 
          AND EXISTS( 
			SELECT	*
			FROM	LAB_MEMBER
			WHERE	MENTOR = NEW.MID 
				AND TYPE = 'Faculty'
		  ))
	THEN
		SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'Students cannot mentor faculty members';
	END IF;
END //

/*
CREATE TRIGGER insert_lab_member_type
AFTER INSERT ON LAB_MEMBER
FOR EACH ROW
BEGIN
	IF NEW.TYPE = 'Student' THEN
		INSERT INTO student (MID, SID, LEVEL, MAJOR)
        VALUES (NEW.MID, NULL, NULL, NULL);
    ELSEIF NEW.TYPE = 'Faculty' THEN
		INSERT INTO faculty (MID, DEPARTMENT)
        VALUES (NEW.MID, NULL);
	ELSE
		INSERT INTO collaborator (MID, AFFILIATION, CV)
        VALUES (NEW.MID, NULL, NULL);
    END IF;
END //
*/

DELIMITER ;